# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deab6a500ee2264985e68a7546d74605ef8d0f5fb6f7bb2852db926110bf317543fe86bd7a619e5e9061e691396e2c6811c7292dbc9eafeb29439b49b32c4fdf

test:
  secret_key_base: b80d8da0fcb67e859c2f3d21011492bc506ff633c11b15ed56bf7a55183328e262a2386602e30d7a306a1f3b8df592c16d61d82c451b1b30a35f2d6016fb5621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
